name: ym_flutter_pcm_sound
description: Send real-time PCM audio (16-bit integer) to your device speakers
version: 1.0.0
homepage: https://github.com/yashmanghnani/ym_flutter_pcm_sound

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_pcm_sound
        pluginClass: FlutterPcmSoundPlugin
      ios:
        pluginClass: FlutterPcmSoundPlugin
      macos:
        pluginClass: FlutterPcmSoundPlugin

